name: knn-donut
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - numpy
  - toolz
  - matplotlib
  - pandas
  - cudatoolkit
  - scikit-learn
  - pytorch
  - torchvision
  - pytorch-lightning
  - timm=0.5.4
  - transformers
  - protobuf
  - datasets
  - nltk
  - pip:
      - donut-python
      - sconf
      - zss